### ISSUE TITLE
Error while using textaSentiment()

### ISSUE THREAD

**Issue by sanchitsood** [philferriere/mscstexta4r#2]
Hi 
After calling the package library(mscstexta4r).
I have set the environment as 
Sys.setenv(MSCS_TEXTANALYTICS_URL="https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment")
 Sys.setenv(MSCS_TEXTANALYTICS_KEY="XXXX")
then ran the code as below(given as an example with the package)

```
library(mscstexta4r)
textaInit()
docsText <- c(
  "Loved the food, service and atmosphere! We'll definitely be back.",
  "Very good food, reasonable prices, excellent service.",
 "It was a great restaurant.",
 "If steak is what you want, this is the place.",
   "The atmosphere is pretty bad but the food is quite good.",
  "The food is quite good but the atmosphere is pretty bad.",
  "I'm not sure I would come back to this restaurant.",
  "The food wasn't very good.",
  "While the food was good the service was a disappointment.",
  "I was very disappointed with both the service and my entree."
)

docsLanguage <- rep("en", length(docsText))
  tryCatch({
    # Perform sentiment analysis
    docsSentiment <- textaSentiment(
      documents = docsText, # Input sentences or documents
      languages = docsLanguage
      # "en"(English, default)|"es"(Spanish)|"fr"(French)|"pt"(Portuguese)
    )
    # Class and structure of docsSentiment
    class(docsSentiment)
    #> [1] "texta"
    str(docsSentiment, max.level = 1)
    #> List of 3
    #> $ results:'data.frame': 10 obs. of 2 variables:
    #> $ json : chr "{\"documents\":[{\"score\":0.9903013,\"id\":\"hDgKc\", __truncated__ }]}
    #> $ request:List of 7
    #> ..- attr(*, "class")= chr "request"
    #> - attr(*, "class")= chr "texta"
    # Print results
    docsSentiment
    #> texta [https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/sentiment]

  },     error = function(err) {
    # Print error
    geterrmessage()
  })
## End(Not run)
```

I get an error "**mscstexta4r: Not Found (HTTP 404). - { \"statusCode\": 404, \"message\": \"Resource not found\" }"**

**Comment by philferriere** [comment]
Hi Sanchit,

Per the package documentation, the MSCS Text Analysis endpoint base URL is:

"https://westus.api.cognitive.microsoft.com/texta/analytics/v2.0/"

It is not:

"https://westus.api.cognitive.microsoft.com/texta/analytics/v2.0/sentiment"

mscstexta4r will add the proper verb based on which API function you want to use.

Hope this helps!

**Comment by nickbeihoff** [comment]
I've run into the exact same error.  However I copied the URL you supplied.

`Sys.setenv(MSCS_TEXTANALYTICS_URL = "https://westus.api.cognitive.microsoft.com/texta/analytics/v2.0/")
Sys.setenv(MSCS_TEXTANALYTICS_KEY = "XXXX")
library(mscstexta4r)
textaInit()

docsText <- c(
  "Loved the food, service and atmosphere! We'll definitely be back.",
  "Very good food, reasonable prices, excellent service.",
  "It was a great restaurant.",
  "If steak is what you want, this is the place.",
  "The atmosphere is pretty bad but the food is quite good.",
  "The food is quite good but the atmosphere is pretty bad.",
  "The food wasn't very good.",
  "I'm not sure I would come back to this restaurant.",
  "While the food was good the service was a disappointment.",
  "I was very disappointed with both the service and my entree."
)
docsLanguage <- rep("en", length(docsText))

tryCatch({
    # Perform sentiment analysis
  textaSentiment(
    documents = docsText,    # Input sentences or documents
    languages = docsLanguage
    # "en"(English, default)|"es"(Spanish)|"fr"(French)|"pt"(Portuguese)
  )
  }, error = function(err) {
    # Print error
  geterrmessage()
  })`

`[1] "mscstexta4r: Not Found (HTTP 404). - { \"statusCode\": 404, \"message\": \"Resource not found\" }"`

I've tried requesting new API keys, creating the .mscskeys.json file, nothing has helped.  Hopefully it's just been a long day and I'm overlooking a simple solution.

**Comment by philferriere** [comment]
Nick,

Can you please run `sessionInfo()` and update your post with the results?

Since I'm still unable to repro, would you mind trying the following steps?

1/ Install the chrome postman extension from [here](https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en)

2/ Build a new HTTP request as follows:

![](https://dl.dropboxusercontent.com/u/5888080/PostmanSentimentHeader.png)

Create a header key named `Ocp-Apim-Subscription-Key` and enter your secret key as the value.

![](https://dl.dropboxusercontent.com/u/5888080/PostmanSentimentBody.png)

Here's the JSON to use for the body of the request (just use copy and paste):

``` json
{
    "documents": [
        {
            "language": "en",
            "id": "1",
            "text": "Loved the food, service and atmosphere! We'll definitely be back."
        },
        {
            "language": "en",
            "id": "2",
            "text": "Very good food, reasonable prices, excellent service."
        }
    ]
}
```

3/ Click the `Send` button

4/ Confirm that you get results similar to:

![](https://dl.dropboxusercontent.com/u/5888080/PostmanSentimentResults.png)

Thanks for your help with this!

**Comment by nickbeihoff** [comment]
Phil,

`sessionInfo()`
Returns:

```
R version 3.2.5 (2016-04-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] Rblpapi_0.3.4       mscstexta4r_0.1.2   textcat_1.0-4       dismo_1.0-15       
 [5] raster_2.5-2        sp_1.2-3            maps_3.1.0          doParallel_1.0.10  
 [9] iterators_1.0.8     foreach_1.4.3       coreNLP_0.4-1       parsent_0.1.0      
[13] ggplot2_2.1.0       syuzhet_1.0.0       stringr_1.0.0       RJSONIO_1.3-0      
[17] RCurl_1.95-4.8      bitops_1.0-6        wordcloud_2.5       RColorBrewer_1.1-2 
[21] tm_0.6-2            NLP_0.1-9           httr_1.2.0          twitteR_1.1.9      
[25] RevoUtilsMath_3.2.5

loaded via a namespace (and not attached):
 [1] slam_0.1-32      pander_0.6.0     rJava_0.9-8      lattice_0.20-33  colorspace_1.2-6
 [6] XML_3.98-1.4     DBI_0.4-1        bit64_0.9-5      tau_0.0-18       plyr_1.8.4      
[11] munsell_0.4.3    gtable_0.2.0     codetools_0.2-14 curl_0.9.7       Rcpp_0.12.5     
[16] openssl_0.9.4    scales_0.4.0     plotrix_3.6-2    jsonlite_0.9.22  bit_1.1-12      
[21] digest_0.6.9     rjson_0.2.15     stringi_1.1.1    dplyr_0.4.3      grid_3.2.5      
[26] tools_3.2.5      magrittr_1.5     rsconnect_0.4.3  assertthat_0.1   R6_2.1.2        
```

When I run the Postman request the same error is returned.

```
{
  "statusCode": 404,
  "message": "Resource not found"
}
```

**Comment by philferriere** [comment]
Thank you for the detailed info, Nick. 

The list of packages looks fine to me. As you've probably already figured out by now, the fact that you see the exact same 404 error using Postman suggests that the problem is unrelated to {mscstexta4r}. 

Is it an issue with your subscription? A geolocation lock perhaps -- does Microsoft only allow access to its API from certain locations??

I can only recommend that you get in touch with Microsoft Cognitive Services directly to get to the bottom of this.

Good luck!

**Comment by nickbeihoff** [comment]
Thanks for the help Phil.  I've reached out to the Microsoft Cognitive Services team to resolve this.
