### ISSUE TITLE
mscstexta4r R package

### ISSUE THREAD

**Issue by jorgefresneda** [philferriere/mscstexta4r#3]
Hi again Phil,

Sorry to bother you again. 

I installed the 'mscstexta4r' library as regularly (dependencies=TRUE). I have a MSCS account through Azure and the Text Analytics API is selected (of course with 0 calls, 0 errors, etc.). I have the keys there.

When I try to start by using 'textaInit()' I get the following error 'Error: mscstexta4r: could not load config info from Sys env nor from file'. So I've never had the chance to enter my API key. I know you showed this error while explaining the use of 'tryCatch()', but you never showed how to solve it.

I'm sorry, but I have no idea of what to do. I'm a complete rookie using APIs.

Thank you very much in advance!

Best,

Jorge

**Comment by philferriere** [comment]
Hi Jorge,
Thank you for trying this package.
Per https://github.com/philferriere/mscstexta4r#package-loading-and-configuration, you provide your key to the package using one of two different mechanisms:
- environment variables
- or, using a file called ".mscskeys.json"
 
Which one are you using?

**Comment by jorgefresneda** [comment]
Hi Phil.

Thank you! I used the following:

Sys.setenv(MSCS_TEXTANALYTICS_URL="https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/", MSCS_TEXTANALYTICS_KEY= "[...]")

But know I get the following error when I try to implement my topic detection:

Error: mscstexta4r: client error: (404) Not Found - { "statusCode": 404, "message": "Resource not found" }

I'm using my desktop computer at the university (I have my account through the university, so it cannot be a location problem). I really don't know what else I can do...   :(

**Comment by philferriere** [comment]
To help me narrow down the issue, I'd like to know if:
* you are able to make it work using the file-based initialization mechanism
* you are able to make it work using global system environment variables

Thanks for your help with this, Jorge.

**Comment by allenj0321** [comment]
I had them same issue, changed the API key.

**Comment by philferriere** [comment]
Good to know, Allen.

Closing this issue since I haven't heard back from Jorge.
